# Import library

In [ ]:
import pandas as pd
import os
from IPython.display import display, HTML
from google.colab import files
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.preprocessing import LabelEncoder

# Membuat Data Sample

## Menggunakan data Prediksi Stroke

In [ ]:
# Memuat file CSV
file_path = os.path.join(os.getcwd(), 'healthcare-dataset-stroke-data.csv')

if not os.path.exists(file_path):
    print(f"Error: File '{file_path}' tidak ditemukan.")
else:
    # Memuat data jika file ditemukan
    data = pd.read_csv(file_path)

    # Mengecek distribusi nilai pada kolom 'stroke'
    stroke_counts = data['stroke'].value_counts()
    print(f"Distribusi nilai pada kolom 'stroke': \n{stroke_counts}\n")

    # Menghapus baris dengan data NULL
    data_clean = data.dropna()

    # Menghapus baris duplikat
    data_clean = data_clean.drop_duplicates()

    # Memisahkan data berdasarkan nilai kolom 'stroke'
    stroke_1_data = data_clean[data_clean['stroke'] == 1]
    stroke_0_data = data_clean[data_clean['stroke'] == 0]

    # Mengecek jumlah data per kategori
    print(f"Jumlah data dengan stroke = 1: {len(stroke_1_data)}")
    print(f"Jumlah data dengan stroke = 0: {len(stroke_0_data)}")

    # Memastikan dataset cukup besar untuk masing-masing kategori
    if len(stroke_1_data) >= 500 and len(stroke_0_data) >= 500:
        # Memilih 500 baris secara acak dari masing-masing kategori
        stroke_1_sample = stroke_1_data.sample(n=500, random_state=42)
        stroke_0_sample = stroke_0_data.sample(n=500, random_state=42)

        # Menggabungkan kedua sampel
        data_sample = pd.concat([stroke_1_sample, stroke_0_sample])

        # Menyimpan data ke session files Google Colab
        output_path = '/content/healthcare-dataset-stroke-sample-1000.csv'
        data_sample.to_csv(output_path, index=False)
        print(f"Data Berhasil disimpan di session files dengan Nama : {output_path}")

        # Menampilkan head dari data sample
        display(data_sample.head(10))

        # Menyediakan link untuk mengunduh file
        print(f"Klik link berikut untuk mengunduh file data sample: ")
        files.download(output_path)
    else:
        print("Dataset tidak memiliki cukup baris untuk masing-masing kategori stroke.")

Distribusi nilai pada kolom 'stroke':
stroke
0    4861
1     249
Name: count, dtype: int64

Jumlah data dengan stroke = 1: 209
Jumlah data dengan stroke = 0: 4700
Dataset tidak memiliki cukup baris untuk masing-masing kategori stroke.

## Menggunakan data Nasa Prediksi Tingkat Bahaya Meteor

In [28]:
# Memuat file CSV yang telah di-upload di session files
# file_path = pd.read_csv("https://raw.githubusercontent.com/Ram4UnMi/Asteroid-Prediction/blob/main/nasa.csv")
file_path = os.path.join(os.getcwd(), 'nasa.csv')

if not os.path.exists(file_path):
    print(f"Error: File '{file_path}' tidak ditemukan.")
else:
    # Memuat data jika file ditemukan
    data = pd.read_csv(file_path)

    # Menampilkan kolom-kolom yang ada di data untuk memilih atribut yang penting
    print("Kolom yang tersedia di dataset:")
    print(data.columns)

    # Menghapus atribut yang tidak terlalu penting
    columns_to_keep = [
        'Neo Reference ID', 'Name', 'Absolute Magnitude', 'Est Dia in KM(min)',
        'Est Dia in KM(max)', 'Close Approach Date', 'Relative Velocity km per sec',
        'Miss Dist.(Astronomical)', 'Miss Dist.(kilometers)', 'Orbit ID',
        'Orbit Determination Date', 'Orbit Uncertainity', 'Minimum Orbit Intersection',
        'Hazardous', 'Epoch Osculation', 'Eccentricity', 'Semi Major Axis',
        'Inclination', 'Aphelion Dist', 'Perihelion Time', 'Mean Anomaly'
    ]

    # Memastikan semua kolom yang dipilih ada di dataset
    missing_columns = [col for col in columns_to_keep if col not in data.columns]
    if missing_columns:
        print(f"Error: The following columns are not found in the dataset: {missing_columns}")
    else:
        # Memilih hanya kolom-kolom yang relevan
        data_clean = data[columns_to_keep]

        # Memisahkan data berdasarkan nilai kolom 'Hazardous' (0 dan 1)
        hazardous_data = data_clean[data_clean['Hazardous'] == 1]
        non_hazardous_data = data_clean[data_clean['Hazardous'] == 0]

        # Mengecek jumlah data per kategori
        print(f"Jumlah data dengan hazardous = 1 (True): {len(hazardous_data)}")
        print(f"Jumlah data dengan hazardous = 0 (False): {len(non_hazardous_data)}")

        # Memastikan dataset cukup besar untuk masing-masing kategori
        if len(hazardous_data) >= 500 and len(non_hazardous_data) >= 500:
            # Memilih 500 baris secara acak dari masing-masing kategori
            hazardous_sample = hazardous_data.sample(n=500, random_state=42)
            non_hazardous_sample = non_hazardous_data.sample(n=500, random_state=42)

            # Menggabungkan kedua sampel
            data_sample = pd.concat([hazardous_sample, non_hazardous_sample])

            # Menyimpan data ke session files Google Colab
            output_path = '/content/asteroid_sample_data.csv'
            data_sample.to_csv(output_path, index=False)
            print(f"Data Berhasil disimpan di session files dengan Nama : {output_path}")

            # Menampilkan head dari data sample
            display(data_sample.head(10))

            # Menyediakan link untuk mengunduh file
            print(f"Data sample berikut telah diunduh...")
            files.download(output_path)
        else:
            print("Dataset tidak memiliki cukup baris untuk masing-masing kategori hazardous.")

Kolom yang tersedia di dataset:
Index(['Neo Reference ID', 'Name', 'Absolute Magnitude', 'Est Dia in KM(min)',
       'Est Dia in KM(max)', 'Est Dia in M(min)', 'Est Dia in M(max)',
       'Est Dia in Miles(min)', 'Est Dia in Miles(max)',
       'Est Dia in Feet(min)', 'Est Dia in Feet(max)', 'Close Approach Date',
       'Epoch Date Close Approach', 'Relative Velocity km per sec',
       'Relative Velocity km per hr', 'Miles per hour',
       'Miss Dist.(Astronomical)', 'Miss Dist.(lunar)',
       'Miss Dist.(kilometers)', 'Miss Dist.(miles)', 'Orbiting Body',
       'Orbit ID', 'Orbit Determination Date', 'Orbit Uncertainity',
       'Minimum Orbit Intersection', 'Jupiter Tisserand Invariant',
       'Epoch Osculation', 'Eccentricity', 'Semi Major Axis', 'Inclination',
       'Asc Node Longitude', 'Orbital Period', 'Perihelion Distance',
       'Perihelion Arg', 'Aphelion Dist', 'Perihelion Time', 'Mean Anomaly',
       'Mean Motion', 'Equinox', 'Hazardous'],
      dtype='object')
Jumlah data dengan hazardous = 1 (True): 755
Jumlah data dengan hazardous = 0 (False): 3932
Data Berhasil disimpan di session files dengan Nama : /content/asteroid_sample_data.csv

,Neo Reference ID,Name,Absolute Magnitude,Est Dia in KM(min),Est Dia in KM(max),Close Approach Date,Relative Velocity km per sec,Miss Dist.(Astronomical),Miss Dist.(kilometers),Orbit ID,Orbit Determination Date,Orbit Uncertainity,Minimum Orbit Intersection,Hazardous,Epoch Osculation,Eccentricity,Semi Major Axis,Inclination,Aphelion Dist,Perihelion Time,Mean Anomaly
1487,3624741,3624741,19.0,0.421265,0.941976,2003-12-22,35.642789,0.381349,57048936.0,24,2017-04-06 08:47:08,3,0.015962,True,2458000.5,0.770621,2.752302,24.819218,4.873285,2.458043e+06,350.868981
3016,3553279,3553279,21.8,0.116026,0.259442,2011-01-22,8.569463,0.164173,24559884.0,19,2017-04-06 08:55:18,4,0.021432,True,2458000.5,0.439061,1.285815,5.530382,1.850366,2.457762e+06,161.174489
160,3102683,3102683,22.1,0.101054,0.225964,1995-12-22,12.111927,0.373986,55947568.0,12,2017-04-06 09:15:45,1,0.011359,True,2458000.5,0.556734,1.006606,0.848196,1.567017,2.458094e+06,268.346526
359,3409688,3409688,21.7,0.121494,0.271669,1997-06-08,8.621147,0.211909,31701134.0,67,2017-04-06 09:03:36,0,0.037331,True,2458000.5,0.225975,1.350962,8.177686,1.656246,2.458043e+06,333.295612
2733,3604618,3604618,21.6,0.127220,0.284472,2009-11-08,22.322119,0.349050,52217160.0,9,2017-04-06 08:49:44,7,0.040221,True,2458000.5,0.488486,1.637953,8.625025,2.438070,2.458251e+06,242.323034
798,3591722,3591722,21.3,0.146068,0.326618,2000-01-15,14.532756,0.155161,23211748.0,18,2017-04-06 08:51:40,6,0.019700,True,2458000.5,0.092590,1.059755,27.070953,1.157878,2.458054e+06,311.359736
1300,3646599,3646599,19.5,0.334622,0.748238,2002-12-15,27.462053,0.470869,70440928.0,74,2016-12-31 06:19:01,1,0.023727,True,2457800.5,0.425256,0.959555,18.148679,1.367611,2.457825e+06,334.235113
1872,3102683,3102683,22.1,0.101054,0.225964,2005-12-15,24.510323,0.214295,32058020.0,12,2017-04-06 09:15:45,1,0.011359,True,2458000.5,0.556734,1.006606,0.848196,1.567017,2.458094e+06,268.346526
3413,2359170,2359170,20.0,0.265800,0.594347,2012-08-15,20.441644,0.283177,42362716.0,24,2017-04-06 09:22:53,1,0.035022,True,2458000.5,0.465548,1.544969,11.909114,2.264226,2.458306e+06,203.339611
4083,3124996,3124996,20.3,0.231502,0.517654,2014-11-22,16.306084,0.449644,67265736.0,18,2017-04-22 06:17:04,1,0.019654,True,2458000.5,0.305299,0.770102,4.314709,1.005213,2.457965e+06,51.196800

Data sample berikut telah diunduh...

# Pengkodean

In [ ]:
import pandas as pd
import os
from IPython.display import display, HTML
from google.colab import files

# Memuat file CSV yang telah di-upload di session files
file_path = '/content/asteroid_sample_data.csv'

if not os.path.exists(file_path):
    print(f"Error: File '{file_path}' tidak ditemukan.")
else:
    # Memuat data jika file ditemukan
    data = pd.read_csv(file_path)

    # Mapping nilai untuk kolom 'Hazardous' (True menjadi 1, False menjadi 0)
    hazardous_map = {True: 1, False: 0}
    data['Hazardous'] = data['Hazardous'].map(hazardous_map)

    # Menyimpan data yang telah diubah ke file baru di session files
    output_path = '/content/asteroid_sample_data_mapped.csv'
    data.to_csv(output_path, index=False)
    print(f"Data Berhasil disimpan di session files dengan Nama : {output_path}")

    # Menampilkan keterangan
    print("           KETERANGAN")
    print("-----------------------------------")
    print("Kolom Hazardous:    0 = False")
    print("                    1 = True")
    print("-----------------------------------")

    # Menampilkan head dari data sample yang sudah dimodifikasi
    display(data.head(10))

    # Menyediakan link untuk mengunduh file
    print(f"Data sample berikut telah diunduh...")
    files.download(output_path)

Data Berhasil disimpan di session files dengan Nama : /content/asteroid_sample_data_mapped.csv
           KETERANGAN
-----------------------------------
Kolom Hazardous:    0 = False
                    1 = True
-----------------------------------

,Neo Reference ID,Name,Absolute Magnitude,Est Dia in KM(min),Est Dia in KM(max),Close Approach Date,Relative Velocity km per sec,Miss Dist.(Astronomical),Miss Dist.(kilometers),Orbit ID,...,Orbit Uncertainity,Minimum Orbit Intersection,Hazardous,Epoch Osculation,Eccentricity,Semi Major Axis,Inclination,Aphelion Dist,Perihelion Time,Mean Anomaly
0,3624741,3624741,19.0,0.421265,0.941976,2003-12-22,35.642789,0.381349,57048936.0,24,...,3,0.015962,1,2458000.5,0.770621,2.752302,24.819218,4.873285,2.458043e+06,350.868981
1,3553279,3553279,21.8,0.116026,0.259442,2011-01-22,8.569463,0.164173,24559884.0,19,...,4,0.021432,1,2458000.5,0.439061,1.285815,5.530382,1.850366,2.457762e+06,161.174489
2,3102683,3102683,22.1,0.101054,0.225964,1995-12-22,12.111927,0.373986,55947568.0,12,...,1,0.011359,1,2458000.5,0.556734,1.006606,0.848196,1.567017,2.458094e+06,268.346526
3,3409688,3409688,21.7,0.121494,0.271669,1997-06-08,8.621147,0.211909,31701134.0,67,...,0,0.037331,1,2458000.5,0.225975,1.350962,8.177686,1.656246,2.458043e+06,333.295612
4,3604618,3604618,21.6,0.127220,0.284472,2009-11-08,22.322119,0.349050,52217160.0,9,...,7,0.040221,1,2458000.5,0.488486,1.637953,8.625025,2.438070,2.458251e+06,242.323034
5,3591722,3591722,21.3,0.146068,0.326618,2000-01-15,14.532756,0.155161,23211748.0,18,...,6,0.019700,1,2458000.5,0.092590,1.059755,27.070953,1.157878,2.458054e+06,311.359736
6,3646599,3646599,19.5,0.334622,0.748238,2002-12-15,27.462053,0.470869,70440928.0,74,...,1,0.023727,1,2457800.5,0.425256,0.959555,18.148679,1.367611,2.457825e+06,334.235113
7,3102683,3102683,22.1,0.101054,0.225964,2005-12-15,24.510323,0.214295,32058020.0,12,...,1,0.011359,1,2458000.5,0.556734,1.006606,0.848196,1.567017,2.458094e+06,268.346526
8,2359170,2359170,20.0,0.265800,0.594347,2012-08-15,20.441644,0.283177,42362716.0,24,...,1,0.035022,1,2458000.5,0.465548,1.544969,11.909114,2.264226,2.458306e+06,203.339611
9,3124996,3124996,20.3,0.231502,0.517654,2014-11-22,16.306084,0.449644,67265736.0,18,...,1,0.019654,1,2458000.5,0.305299,0.770102,4.314709,1.005213,2.457965e+06,51.196800

Data sample berikut telah diunduh...

# Normalisasi

In [ ]:
# Memuat file CSV yang telah di-upload di session files
file_path = '/content/asteroid_sample_data_mapped.csv'

if not os.path.exists(file_path):
    print(f"Error: File '{file_path}' tidak ditemukan.")
else:
    # Memuat data jika file ditemukan
    data = pd.read_csv(file_path)

    # Menghapus baris dengan data NULL
    data_clean = data.dropna()

    # Menghapus baris duplikat
    data_clean = data_clean.drop_duplicates()

    # Menghapus kolom yang tidak relevan (jika ada kolom tambahan yang tidak diperlukan)
    data_clean = data_clean.drop(columns=['Orbiting Body', 'Equinox'], errors='ignore')

    # Normalisasi kolom tertentu menggunakan Min-Max Scaler
    scaler = MinMaxScaler()

    # Pilih kolom-kolom yang relevan untuk normalisasi (angka atau data yang bisa dinormalisasi)
    columns_to_normalize = [
        'Est Dia in KM(min)', 'Est Dia in KM(max)', 'Est Dia in M(min)', 'Est Dia in M(max)',
        'Est Dia in Miles(min)', 'Est Dia in Miles(max)', 'Relative Velocity km per sec',
        'Relative Velocity km per hr', 'Miss Dist.(Astronomical)', 'Miss Dist.(lunar)',
        'Miss Dist.(kilometers)', 'Miss Dist.(miles)', 'Inclination', 'Orbital Period', 'Perihelion Distance',
        'Perihelion Arg', 'Aphelion Dist', 'Perihelion Time', 'Mean Anomaly', 'Mean Motion'
    ]

    # Pastikan kolom yang akan dinormalisasi ada di dataset
    columns_to_normalize = [col for col in columns_to_normalize if col in data_clean.columns]
    data_clean[columns_to_normalize] = scaler.fit_transform(data_clean[columns_to_normalize])

    # Membulatkan hasil normalisasi ke 2 desimal
    data_clean[columns_to_normalize] = data_clean[columns_to_normalize].round(2)

    # Memisahkan data berdasarkan nilai kolom 'Hazardous' (True=1, False=0)
    hazardous_data = data_clean[data_clean['Hazardous'] == 1]
    non_hazardous_data = data_clean[data_clean['Hazardous'] == 0]

    # Debugging jumlah data
    print(f"Jumlah data 'Hazardous = 1': {len(hazardous_data)}")
    print(f"Jumlah data 'Hazardous = 0': {len(non_hazardous_data)}")

    # Memastikan dataset cukup besar untuk masing-masing kategori
    if len(hazardous_data) >= 500 and len(non_hazardous_data) >= 500:

        # Memilih 500 baris secara acak dari masing-masing kategori
        hazardous_sample = hazardous_data.sample(n=500, random_state=42)
        non_hazardous_sample = non_hazardous_data.sample(n=500, random_state=42)

        # Menggabungkan kedua sampel
        data_sample = pd.concat([hazardous_sample, non_hazardous_sample])

        # Menyimpan data ke file baru
        output_path = '/content/asteroid_sample_data_normalized.csv'
        data_sample.to_csv(output_path, index=False)
        print(f"Data Berhasil disimpan di session files dengan Nama : {output_path}")

        # Menampilkan data dengan scroll horizontal
        display(HTML(f'<div style="overflow-x: auto; width: 100%;">{data_sample.head(10).to_html(index=False)}</div>'))
    else:
        print("Dataset tidak memiliki cukup baris untuk masing-masing kategori Hazardous.")

Jumlah data 'Hazardous = 1': 500
Jumlah data 'Hazardous = 0': 500
Data Berhasil disimpan di session files dengan Nama : /content/asteroid_sample_data_normalized.csv

# Seleksi Fitur

In [ ]:
# Memuat file dataset yang sudah dinormalisasi
file_input = '/content/asteroid_sample_data_normalized.csv'
data = pd.read_csv(file_input)

# Memeriksa tipe data untuk menemukan kolom yang perlu diubah
print(data.dtypes)

# Mengonversi kolom tanggal 'Close Approach Date' menjadi angka (jumlah hari sejak tanggal tertentu)
if 'Close Approach Date' in data.columns:
    data['Close Approach Date'] = pd.to_datetime(data['Close Approach Date'], errors='coerce')
    data['Close Approach Date'] = (data['Close Approach Date'] - pd.Timestamp("1970-01-01")) // pd.Timedelta('1D')

# Pastikan 'Hazardous' adalah kolom target
target_column = 'Hazardous'

# Mengonversi kolom target jika berupa kategori
if data[target_column].dtype == 'object':
    le = LabelEncoder()
    data[target_column] = le.fit_transform(data[target_column])

# Memisahkan fitur dan target
X = data.drop(columns=[target_column])
y = data[target_column]

# Mengonversi kolom non-numerik menjadi numerik (jika ada)
for col in X.select_dtypes(include=['object']).columns:
    le = LabelEncoder()
    X[col] = le.fit_transform(X[col])

# Seleksi fitur menggunakan f_classif (ANOVA F-test)
k_best = SelectKBest(score_func=f_classif, k='all')  # Atau pilih k tertentu
k_best.fit(X, y)

# Membuat dataframe baru dengan skor fitur
feature_scores = pd.DataFrame({
    'Feature': X.columns,
    'Score': k_best.scores_
}).sort_values(by='Score', ascending=False).reset_index(drop=True)

# Menambahkan kolom nomor urut
feature_scores.insert(0, 'No', range(1, len(feature_scores) + 1))

# Menambahkan kolom untuk keterangan fitur yang dipilih
mean_score = feature_scores['Score'].mean()
feature_scores['Selected'] = feature_scores['Score'] > mean_score
feature_scores['Selected'] = feature_scores['Selected'].replace({True: 'Yes', False: 'No'})

# Mengatur Pandas untuk menampilkan semua kolom
pd.set_option('display.max_columns', None)

# Menampilkan tabel HTML dengan semua kolom
display(HTML(f'<div style="overflow-x: auto; width: 100%;">{feature_scores.to_html(index=False, border=1)}</div>'))

# Memilih fitur yang memiliki skor lebih besar dari rata-rata
selected_features = feature_scores[feature_scores['Selected'] == 'Yes']['Feature']

# Membuat dataset baru dengan fitur terpilih
X_selected = X[selected_features]
X_selected = pd.concat([X_selected, y], axis=1)

# Menyimpan hasil ke file baru
output_path = '/content/asteroid_sample_data_selected_features.csv'
X_selected.to_csv(output_path, index=False)
print(f"Dataset dengan fitur terpilih telah disimpan di {output_path}")

Neo Reference ID                  int64
Name                              int64
Absolute Magnitude              float64
Est Dia in KM(min)              float64
Est Dia in KM(max)              float64
Close Approach Date              object
Relative Velocity km per sec    float64
Miss Dist.(Astronomical)        float64
Miss Dist.(kilometers)          float64
Orbit ID                          int64
Orbit Determination Date         object
Orbit Uncertainity                int64
Minimum Orbit Intersection      float64
Hazardous                         int64
Epoch Osculation                float64
Eccentricity                    float64
Semi Major Axis                 float64
Inclination                     float64
Aphelion Dist                   float64
Perihelion Time                 float64
Mean Anomaly                    float64
dtype: object

Dataset dengan fitur terpilih telah disimpan di /content/asteroid_sample_data_selected_features.csv